#!/bin/bash

# Raise volume by 5% in PulseAudio

pactl set-sink-volume 0 $(echo '('$(pactl list | grep 'Volume' | head -n 1 |
  grep -o '[0-9]*%' | head -n 1 | sed -e 's/%//')'-5)/5*5' | bc)'%'
pactl list | grep Volume | head -n 1 | grep -o '[0-9]*%' | head -n 1 | dzen2 -p 1 -x -100 -y 20 -w 50 -h 50
